#!/bin/sh
# Cleans-up after the old HoRDNIS installations.
# These would install into both /Library/Extensions and
# /System/Library/Extensions, while we only use the former location.
# touch /Library/Extensions
exit 0
